In [1]:
# Python packages
import scanpy as sc
import anndata as ad
import SEACells
from SEACells.core import summarize_by_SEACell
import pickle
import pandas as pd
import os 
import numpy as np
from os.path import join

# Split the simulation data by "Batch"

In [2]:
samplesheet_orig = pd.read_json("/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/samplesheet.json")
samplesheet_orig.head()

,seed,lib.loc,dropout.type,dropout.shape,dropout.mid,batchCells,batch.facLoc,batch.facScale,group.prob,de.prob,de.facLoc,de.facScale,sim,sample_name,file_path,sparsity
0,1,12,experiment,-5,0.5000,"[10000, 10000, 10000, 10000, 10000, 10000]","[0.1, 0.15, 0.12, 0.18, 0.15, 0.25]","[0.1, 0.08, 0.12, 0.1, 0.12, 0.18]","[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.142...","[0.1, 0.12, 0.08, 0.2, 0.12, 0.1, 0.16]","[0.1, 0.08, 0.12, 0.18, 0.06, 0.2, 0.14]","[0.4, 0.30000000000000004, 0.45, 0.48, 0.42, 0...",sim1,sim1_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,48.37
1,1,12,experiment,-5,0.8333,"[10000, 10000, 10000, 10000, 10000, 10000]","[0.1, 0.15, 0.12, 0.18, 0.15, 0.25]","[0.1, 0.08, 0.12, 0.1, 0.12, 0.18]","[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.142...","[0.1, 0.12, 0.08, 0.2, 0.12, 0.1, 0.16]","[0.1, 0.08, 0.12, 0.18, 0.06, 0.2, 0.14]","[0.4, 0.30000000000000004, 0.45, 0.48, 0.42, 0...",sim1,sim1_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,51.00
2,1,12,experiment,-5,1.1667,"[10000, 10000, 10000, 10000, 10000, 10000]","[0.1, 0.15, 0.12, 0.18, 0.15, 0.25]","[0.1, 0.08, 0.12, 0.1, 0.12, 0.18]","[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.142...","[0.1, 0.12, 0.08, 0.2, 0.12, 0.1, 0.16]","[0.1, 0.08, 0.12, 0.18, 0.06, 0.2, 0.14]","[0.4, 0.30000000000000004, 0.45, 0.48, 0.42, 0...",sim1,sim1_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,54.62
3,1,12,experiment,-5,1.5000,"[10000, 10000, 10000, 10000, 10000, 10000]","[0.1, 0.15, 0.12, 0.18, 0.15, 0.25]","[0.1, 0.08, 0.12, 0.1, 0.12, 0.18]","[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.142...","[0.1, 0.12, 0.08, 0.2, 0.12, 0.1, 0.16]","[0.1, 0.08, 0.12, 0.18, 0.06, 0.2, 0.14]","[0.4, 0.30000000000000004, 0.45, 0.48, 0.42, 0...",sim1,sim1_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,59.03
4,1,12,experiment,-5,1.8333,"[10000, 10000, 10000, 10000, 10000, 10000]","[0.1, 0.15, 0.12, 0.18, 0.15, 0.25]","[0.1, 0.08, 0.12, 0.1, 0.12, 0.18]","[0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.142...","[0.1, 0.12, 0.08, 0.2, 0.12, 0.1, 0.16]","[0.1, 0.08, 0.12, 0.18, 0.06, 0.2, 0.14]","[0.4, 0.30000000000000004, 0.45, 0.48, 0.42, 0...",sim1,sim1_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,64.25

In [3]:
samplesheet_orig.columns

Index(['seed', 'lib.loc', 'dropout.type', 'dropout.shape', 'dropout.mid',
       'batchCells', 'batch.facLoc', 'batch.facScale', 'group.prob', 'de.prob',
       'de.facLoc', 'de.facScale', 'sim', 'sample_name', 'file_path',
       'sparsity'],
      dtype='object')

In [4]:
outdir = "/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/SEACells/split_batch"
# RUN ONLY ONCE
# for ind, row in samplesheet_orig.iterrows():
#     adata_path = row.file_path
#     adata = sc.read_h5ad(adata_path)
#     if row.sim == "sim1":
#         batch_key = "Batch"
#     elif row.sim == "sim2":
#         batch_key = "SubBatch"
#     for batch in adata.obs[batch_key].unique():
#         outfile = join(outdir, f"{row.sample_name}_{batch}.h5ad")
#         adata_batch = adata[adata.obs[batch_key] == batch].copy()
#         adata_batch.write_h5ad(outfile)
#         print(f"Saved {outfile}")

In [5]:
outdir = "/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/SEACells/split_batch"

def make_samplesheet(dir):
    files = os.listdir(dir)
    files = [file for file in files if file.endswith(".h5ad") or file.endswith(".h5") or file.endswith(".hdf5")]
    file_paths = [os.path.join(dir, file) for file in files] #[os.path.abspath(
    file_paths = [os.path.abspath(file) for file in file_paths]
    sample_name = [file.split(".h5ad")[0] for file in files]
    df = pd.DataFrame({"sample_name": sample_name, "file_path": file_paths})
    return df

samplesheet = make_samplesheet(outdir)
samplesheet["sim"] = samplesheet.apply(lambda x: "sim2" if "sim2" in x["file_path"] else "sim1", axis = 1)
# samplesheet.to_csv("/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/SEACells/split_batch/samplesheet.csv")
samplesheet_sim1 = samplesheet[samplesheet["sim"] == "sim1"]
samplesheet_sim2 = samplesheet[samplesheet["sim"] == "sim2"]

# samplesheet_sim1.to_csv("/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/SEACells/seacell/samplesheet_sim1.csv")
# samplesheet_sim2.to_csv("/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/SEACells/seacell/samplesheet_sim2.csv")

# Process Sim 2

In [6]:
samplesheet_sim2 = pd.read_csv("/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/SEACells/seacell/samplesheet_sim2.csv", index_col = 0).reset_index(drop = True)

samplesheet_sim2["Batch"] = samplesheet_sim2.file_path.apply(lambda x: x.split(".h5ad")[0])
samplesheet_sim2["Batch"] = samplesheet_sim2.Batch.apply(lambda x: x.split("_")[-1])
samplesheet_sim2["parent_sample"] = samplesheet_sim2.apply(
    lambda x: os.path.basename(x.file_path).split('_' + x.Batch)[0],
    axis=1
)

seacell_dir = "/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/SEACells/seacell"
preprocessed_dir = "/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/SEACells/preprocessed"
# add seacell file path to samplesheet for each sample_name
samplesheet_sim2["seacell_path"] = samplesheet_sim2.sample_name.apply(lambda x: join(seacell_dir, x + "_summarised_seacell.h5ad"))
samplesheet_sim2["model_path"] = samplesheet_sim2["seacell_path"].apply(lambda x: x.replace("summarised_seacell.h5ad", "model.pkl"))
samplesheet_sim2["preprocessed_path"] = samplesheet_sim2.sample_name.apply(lambda x: join(preprocessed_dir, x + "_preprocessed.h5ad"))
samplesheet_sim2.head()
samplesheet_orig = pd.read_json("/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/samplesheet.json")
samplesheet_orig["parent_sample"] = samplesheet_orig["sample_name"]
del samplesheet_orig["sample_name"]
samplesheet_sim2 = samplesheet_sim2.merge(samplesheet_orig.loc[:, ~samplesheet_orig.columns.isin(["seed", "file_path"])], how = "left")

In [7]:
samplesheet_sim2.head()

,sample_name,file_path,sim,Batch,parent_sample,seacell_path,model_path,preprocessed_path,lib.loc,dropout.type,dropout.shape,dropout.mid,batchCells,batch.facLoc,batch.facScale,group.prob,de.prob,de.facLoc,de.facScale,sparsity
0,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2,Batch1Sub1,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,/local/Projects/AAkalin_Neuroblastoma/Results/...,/local/Projects/AAkalin_Neuroblastoma/Results/...,12,experiment,-5,0.5,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",37.67
1,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2,Batch1Sub2,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,/local/Projects/AAkalin_Neuroblastoma/Results/...,/local/Projects/AAkalin_Neuroblastoma/Results/...,12,experiment,-5,0.5,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",37.67
2,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2,Batch1Sub3,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,/local/Projects/AAkalin_Neuroblastoma/Results/...,/local/Projects/AAkalin_Neuroblastoma/Results/...,12,experiment,-5,0.5,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",37.67
3,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2,Batch1Sub4,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,/local/Projects/AAkalin_Neuroblastoma/Results/...,/local/Projects/AAkalin_Neuroblastoma/Results/...,12,experiment,-5,0.5,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",37.67
4,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2,Batch2Sub1,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,/local/Projects/AAkalin_Neuroblastoma/Results/...,/local/Projects/AAkalin_Neuroblastoma/Results/...,12,experiment,-5,0.5,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",37.67

In [8]:
def get_obs_data(h5ad_file_path):
    adata = ad.read_h5ad(h5ad_file_path, backed='r')
    obs_df = adata.obs.copy()
    adata.file.close()
    return obs_df

def get_model_data(model_path):
    with open(model_path, "rb") as f:
        model = pickle.load(f)
        assignments = model["model"].get_hard_assignments()
    return assignments



def calc_celltype_purity(obs_df, assignments):
    obs_df = obs_df.copy()
    obs_df['SEACell'] = assignments
    
    def purity_func(group):
        # Get the counts of each Group in the SEACell
        counts = group['Group'].value_counts()
        # Identify the most common Group and its count
        most_common_group = counts.idxmax()
        most_common_count = counts.max()
        # Total number of cells in the SEACell
        total_count = counts.sum()
        # Calculate purity
        purity = most_common_count / total_count
        return pd.Series({'Group': most_common_group, 'celltype_purity': purity})
    
    # Apply the function to each SEACell group
    result = obs_df.groupby('SEACell').apply(purity_func)
    return result

In [9]:
# example 
obs_df = get_obs_data("/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/SEACells/preprocessed/sim1_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid1.5_Batch6_preprocessed.h5ad")
assignments = get_model_data("/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/SEACells/seacell/sim1_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid1.5_Batch6_model.pkl")

celltype_purity = calc_celltype_purity(obs_df, assignments)

seacell_adata = sc.read_h5ad("/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/SEACells/seacell/sim1_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid1.5_Batch6_summarised_seacell.h5ad")
print(celltype_purity.head())
print(seacell_adata.obs.head())
seacell_adata.obs = seacell_adata.obs.join(celltype_purity, how = "inner")
print(seacell_adata.obs.head())
print(f"number of cells before filtering: {seacell_adata.n_obs}")
seacell_adata = seacell_adata[seacell_adata.obs["celltype_purity"] > 0.95]
print(f"number of cells after filtering: {seacell_adata.n_obs}")

             Group  celltype_purity
SEACell
SEACell-0   Group2              1.0
SEACell-1   Group3              1.0
SEACell-10  Group2              1.0
SEACell-11  Group1              1.0
SEACell-12  Group3              1.0
Empty DataFrame
Columns: []
Index: [SEACell-9, SEACell-14, SEACell-13, SEACell-11, SEACell-17]
             Group  celltype_purity
SEACell-9   Group1         0.520721
SEACell-14  Group1         1.000000
SEACell-13  Group1         1.000000
SEACell-11  Group1         1.000000
SEACell-17  Group1         1.000000
number of cells before filtering: 19
number of cells after filtering: 18

In [10]:
obs_df.head()

,Cell,Batch,Group,ExpLibSize,sum,detected,total,Discard,SEACell
index,,,,,,,,,
Cell51744,Cell51744,Batch6,Group1,164554.190671,157354.0,4148,157354.0,False,SEACell-9
Cell50365,Cell50365,Batch6,Group1,146746.153612,137650.0,3931,137650.0,False,SEACell-9
Cell58832,Cell58832,Batch6,Group1,164682.814742,155834.0,4174,155834.0,False,SEACell-9
Cell58118,Cell58118,Batch6,Group1,181516.634867,174401.0,4352,174401.0,False,SEACell-14
Cell57427,Cell57427,Batch6,Group1,198546.958256,191845.0,4569,191845.0,False,SEACell-14

In [11]:
assignments.head()

              SEACell
index
Cell51744   SEACell-9
Cell50365   SEACell-9
Cell58832   SEACell-9
Cell58118  SEACell-14
Cell57427  SEACell-14

In [12]:
all(assignments.index == obs_df.index) # that means, all elements in the index of assignments are equal to the ones in obs_df so we can just cbind

True

In [17]:
out_merged = "/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/SEACells/merged_seacell_data"
ad_dict = dict()
obs_cols = ['sample_name', 'file_path', 'sim', 'Batch', 'parent_sample',
       'seacell_path', 'lib.loc', 'dropout.type', 'dropout.shape',
       'dropout.mid', 'sparsity']
for ind, row in samplesheet_sim2.iterrows():
    # load seacell adata
    adata = sc.read_h5ad(row.seacell_path)
    # load obs of the original preprocessed dataset
    preprocessed_obs_df = get_obs_data(row.preprocessed_path)
    # load seacell model
    assignments = get_model_data(row.model_path)
    # calculate celltype purity and add it to the obs. Then filter seacells with celltype purity > 0.95
    celltype_purity = calc_celltype_purity(preprocessed_obs_df, assignments)
    adata.obs = adata.obs.join(celltype_purity, how = "inner")
    adata = adata[adata.obs["celltype_purity"] > 0.95]
    
    # add metadata of the simulation to the adata object
    obs_dict = row[obs_cols].to_dict() 
    adata.obs = adata.obs.assign(**obs_dict)
    adata.obs["unique_cell_id"] = adata.obs.apply(lambda x: f"{x.name}_{x.Batch}", axis=1)
    adata.obs_names = adata.obs["unique_cell_id"]
    adata.obs.index = adata.obs["unique_cell_id"]
    
    parent_sample = row.parent_sample
    if not parent_sample in ad_dict.keys():
        ad_dict[parent_sample] = []
    ad_dict[parent_sample].append(adata)

def calculate_sparsity(adata):
    def count_zeros(arr, tol=1e-10):
        return np.sum(np.abs(arr) < tol)
    sparsity = count_zeros(adata.X.toarray()) / float(adata.X.size)
    sparsity = np.round(sparsity, 4) * 100
    return sparsity

ad_dict_concat = dict()
for sample, ads in ad_dict.items():
    ad_dict_concat[sample] = ad.concat(ads, axis = 0)
    ad_dict_concat[sample].obs["seacell_sparsity"] = calculate_sparsity(ad_dict_concat[sample])
    ad_dict_concat[sample].write_h5ad(join(out_merged, f"{sample}_merged_seacell.h5ad"))

In [28]:
for sample in ad_dict["sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5"]:
    print(sample.obs.parent_sample.unique())

['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']
['sim2_DropoutSimulation_dropout.typeexperiment_dropout.shape5_dropout.mid0.5']

# write samplesheet for the benchmarking pipeline

In [23]:
out_merged = "/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/SEACells/merged_seacell_data"

def make_samplesheet(dir):
    files = os.listdir(dir)
    files = [file for file in files if file.endswith(".h5ad") or file.endswith(".h5") or file.endswith(".hdf5")]
    file_paths = [os.path.join(dir, file) for file in files] #[os.path.abspath(
    file_paths = [os.path.abspath(file) for file in file_paths]
    sample_name = [file.split(".h5ad")[0] for file in files]
    df = pd.DataFrame({"sample_name": sample_name, "file_path": file_paths})
    return df

samplesheet_orig = pd.read_json("/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/samplesheet.json")
samplesheet_orig["parent_sample"] = samplesheet_orig["sample_name"]
del samplesheet_orig["sample_name"]
merged_samplesheet = make_samplesheet(out_merged)
merged_samplesheet["parent_sample"] = merged_samplesheet["sample_name"].apply(lambda x: x.split("_merged_seacell")[0])
merged_samplesheet = merged_samplesheet.merge(samplesheet_orig.rename(columns = {"file_path" : "parent_sample_path"}), how = "left")
merged_samplesheet
# def load_and_calculate_sparsity(h5ad_file_path):
#     adata = ad.read_h5ad(h5ad_file_path)
#     def count_zeros(arr, tol=1e-30):
#         return np.sum(np.abs(arr) < tol)
    
#     sparsity = count_zeros(adata.X.toarray()) / float(adata.X.size)
#     sparsity = np.round(sparsity, 4) * 100
#     return sparsity

# merged_samplesheet["merged_seacell_sparsity"] = merged_samplesheet["file_path"].apply(lambda x: load_and_calculate_sparsity(x))

,sample_name,file_path,parent_sample,seed,lib.loc,dropout.type,dropout.shape,dropout.mid,batchCells,batch.facLoc,batch.facScale,group.prob,de.prob,de.facLoc,de.facScale,sim,parent_sample_path,sparsity
0,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,0.5000,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,37.67
1,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,0.8333,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,41.64
2,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,1.1667,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,46.59
3,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,1.5000,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,52.38
4,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,1.8333,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,58.78
5,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,2.1667,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,65.19
6,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,2.5000,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,71.24
7,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,2.8333,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,76.47
8,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,3.1667,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,80.48
9,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,3.5000,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,83.33

In [22]:
merged_samplesheet

,sample_name,file_path,parent_sample,seed,lib.loc,dropout.type,dropout.shape,dropout.mid,batchCells,batch.facLoc,batch.facScale,group.prob,de.prob,de.facLoc,de.facScale,sim,parent_sample_path,sparsity,merged_seacell_sparsity
0,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,0.5000,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,37.67,11.85
1,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,0.8333,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,41.64,13.54
2,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,1.1667,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,46.59,17.32
3,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,1.5000,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,52.38,22.33
4,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,1.8333,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,58.78,25.71
5,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,2.1667,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,65.19,34.93
6,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,2.5000,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,71.24,49.44
7,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,2.8333,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,76.47,67.41
8,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,3.1667,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,80.48,86.31
9,sim2_DropoutSimulation_dropout.typeexperiment_...,/local/Projects/AAkalin_Neuroblastoma/Results/...,sim2_DropoutSimulation_dropout.typeexperiment_...,1,12,experiment,-5,3.5000,"[10000, 10000, 10000, 10000]","[0.2, 0.25, 0.22, 0.28]","[0.1, 0.08, 0.12, 0.1]","[0.25, 0.25, 0.25, 0.25]","[0.1, 0.12, 0.08, 0.2]","[0.1, 0.08, 0.12, 0.18]","[0.4, 0.30000000000000004, 0.45, 0.48]",sim2,/local/Projects/AAkalin_Neuroblastoma/Results/...,83.33,104.02

In [24]:
merged_samplesheet.to_json("/local/Projects/AAkalin_Neuroblastoma/Results/simulate_single_cell/h5ad/with_dropout/SEACells/merged_seacell_data/samplesheet.json", orient='records', indent=2)